apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.appname}}-deploy
  namespace: {{.Values.appname}}
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      app: {{.Values.labelname}}
  template:
    metadata:
      labels:
        app: {{.Values.labelname}}
    spec:
      containers:
        - image: {{.Values.image}}
          name: {{.Values.imagename}}
          ports:
            - containerPort: {{.Values.appport}}

