apiVersion: v1
kind: Service 
metadata:
  name: {{.Values.appname}}-service
spec:
  selector:
    app: {{.Values.labelname}}
  type: ClusterIP
  ports:
    - targetPort: {{.Values.appport}}
      port: 80
