my-app1:
  appname: test-app1
  replicas: 1
  labelname: test
  image: srinadhdkr/nginx:green 
  imagename: nginx
  appport: 80
  ingress:
    enabled: false
my-app2:
  appname: test-app2
  replicas: 1
  labelname: test
  image: srinadhdkr/nginx:blue 
  imagename: nginx
  appport: 80
  ingress:
    enabled: false

